---
name: "Enhanced Caching"
description: "Enhanced caching over the default setup-{language} GH action caching"

inputs:
  cache:
    description: "Package manager cache type"
    required: true
    type: choice
    options:
      - "maven"
      - "sbt"
      - "gradle"
      - "npm"
      - "yarn"

runs:
  using: composite
  steps:
    - uses: actions/cache@v4
      # See https://github.com/actions/setup-java/blob/799ee7c97e9721ef38d1a7e8486c39753b9d6102/src/cache.ts#L25
      name: Setup Maven Caching
      if: ${{ inputs.cache == 'maven' }}
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - uses: actions/cache@v4
      name: Setup SBT Caching
      # See https://github.com/actions/setup-java/blob/799ee7c97e9721ef38d1a7e8486c39753b9d6102/src/cache.ts#L47
      if: ${{ inputs.cache == 'sbt' }}
      with:
        path: |
          ~/.ivy2/cache
          ~/.sbt
          ~/.cache/coursier
          ~/.m2
          !~/.sbt/*.lock
          !~/**/ivydata-*.properties
        key: ${{ runner.os }}-sbt-${{ hashFiles('**/*.sbt', '**/project/build.properties', '**/project/**.scala', '**/project/**.sbt') }}
        restore-keys: |
          ${{ runner.os }}-sbt-

    - uses: actions/cache@v4
      name: Setup Gradle Caching
      # See https://github.com/actions/setup-java/blob/799ee7c97e9721ef38d1a7e8486c39753b9d6102/src/cache.ts#L31
      if: ${{ inputs.cache == 'gradle' }}
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', 'buildSrc/**/Versions.kt', 'buildSrc/**/Dependencies.kt', 'gradle/*.versions.toml', '**/versions.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - uses: actions/cache@v4
      name: Setup NPM Caching
      # See https://github.com/actions/setup-node/blob/802632921f8532d2409ae6eac3313b6f81f11122/src/cache-utils.ts#L22
      if: ${{ inputs.cache == 'npm' }}
      with:
        path: |
          ~/.npm
          **/node_modules
        key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json', 'npm-shrinkwrap.json', 'yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-npm-

    - uses: actions/cache@v4
      name: Setup Yarn Caching
      # See https://github.com/actions/setup-node/blob/802632921f8532d2409ae6eac3313b6f81f11122/src/cache-utils.ts#L40
      if: ${{ inputs.cache == 'yarn' }}
      with:
        path: |
          ~/.config/yarn
          **/node_modules
        key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
